using ElmahCore;

#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElmahCore
{
    using System;
    using System.Collections.Generic;
    
    #line 2 "..\..\AboutPage.cshtml"
    using System.IO;
    
    #line default
    #line hidden
    using System.Linq;
    
    #line 3 "..\..\AboutPage.cshtml"
    using System.Reflection;
    
    #line default
    #line hidden
    using System.Text;
    
    #line 4 "..\..\AboutPage.cshtml"
    
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class AboutPage : WebTemplateBase
    {
#line hidden

        #line 72 "..\..\AboutPage.cshtml"

    private Version GetVersion()
    {
        return GetType().Assembly.GetName().Version;
    }

    private Version GetFileVersion()
    {
        var version = (AssemblyFileVersionAttribute) Attribute.GetCustomAttribute(GetType().Assembly, typeof(AssemblyFileVersionAttribute));
        return version != null ? new Version(version.Version) : new Version();
    }

        #line default
        #line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");






            
            #line 6 "..\..\AboutPage.cshtml"
  
    var basePageName = ElmahRoot;

    const string title = "About ELMAHCore";
    Layout = new ElmahCore.MasterPage
    {
        Context  = Context, /* TODO Consider not requiring this */
        Title    = title,
        ElmahRoot = ElmahRoot,
        ErrorLog = ErrorLog,
        SpeedBarItems = new[]
        {
            SpeedBar.Home.Format(basePageName),
            SpeedBar.Help,
            SpeedBar.About.Format(basePageName)
        },
    };

    var stamps = SccStamp.FindAll(typeof (ErrorLog).Assembly)
                          .OrderByDescending(s => s.Revision)
                          .ToArray();
        

            
            #line default
            #line hidden


WriteLiteral(@"This <strong>");


            
            #line 60 "..\..\AboutPage.cshtml"
            Write(Build.TypeLowercase);

            
            #line default
            #line hidden
WriteLiteral("</strong>\r\n    ");


            
            #line 61 "..\..\AboutPage.cshtml"
Write(stamps.Any() ? "(SCC #" + stamps.First().Revision.ToString("N0") + ")" : null);

            
            #line default
            #line hidden
WriteLiteral("\r\n    build was compiled from the following sources for CLR ");


            
            #line 62 "..\..\AboutPage.cshtml"
                                                     Write(Build.ImageRuntimeVersion);

            
            #line default
            #line hidden
WriteLiteral(":\r\n</p>\r\n\r\n<ul>\r\n");


            
            #line 66 "..\..\AboutPage.cshtml"
     foreach (var stamp in stamps)
    {

            
            #line default
            #line hidden
WriteLiteral("        <li><code>");


            
            #line 68 "..\..\AboutPage.cshtml"
             Write(stamp.Id);

            
            #line default
            #line hidden
WriteLiteral("</code></li>        \r\n");


            
            #line 69 "..\..\AboutPage.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("</ul>\r\n");


WriteLiteral("\r\n");


        }
    }
}
#pragma warning restore 1591
