#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElmahCore.Mvc.PoweredBy
{
	[System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class PoweredBy : RazorTemplateBase
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");



            
            #line 3 "..\..\PoweredBy.cshtml"
  
    var about = GetAbout((version, fileVersion, product, copyright) => new
    {
        Version   = version != null
                  ? version.ToString()
                  : fileVersion != null 
                  ? fileVersion.ToString() 
                  : "?.?.?.?",
        Product   = (product ?? "(product)"),
        Copyright = copyright,
    });

            
            #line default
            #line hidden
WriteLiteral("<span>\r\n    Based on <a href=\"https://elmah.github.io/\">Elmah</a>, Powered by <a href=\"https://github.com/ElmahCore/www\">");


            
            #line 15 "..\..\PoweredBy.cshtml"
                                             Write(about.Product);

            
            #line default
            #line hidden
WriteLiteral("</a>,\r\n    version ");


            
            #line 16 "..\..\PoweredBy.cshtml"
       Write(about.Version);

            
            #line default
            #line hidden

            
            #line 16 "..\..\PoweredBy.cshtml"
                            
#if DEBUG

            
            #line default
            #line hidden
WriteLiteral(" (");


            
            #line 18 "..\..\PoweredBy.cshtml"
   Write("Build.Configuration");

            
            #line default
            #line hidden
WriteLiteral(")");


            
            #line 18 "..\..\PoweredBy.cshtml"
                                    #endif
    
            
            #line default
            #line hidden
WriteLiteral(".\r\n    ");


            
            #line 20 "..\..\PoweredBy.cshtml"
Write(about.Copyright);

            
            #line default
            #line hidden
WriteLiteral("\r\n    Licensed under <a href=\"http://www.apache.org/licenses/LICENSE-2.0\">Apache " +
"License, Version 2.0</a>.\r\n</span>\r\n");


        }
    }
}
#pragma warning restore 1591
