name: Build

on:
  workflow_dispatch:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: tree:0

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: NPM Install
        working-directory: ui
        run: npm ci
          
      - name: NPM Lint
        working-directory: ui
        run: npm run lint
          
      - name: NPM Build
        working-directory: ui
        run: npm run build
          
      - uses: actions/setup-dotnet@v3

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --no-restore --verbosity normal
