name: dotnet package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: NPM Install
        working-directory: ui
        run: npm install
          
      - name: NPM Lint
        working-directory: ui
        run: npm run lint
          
      - name: NPM Build
        working-directory: ui
        run: npm run build
          
      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --no-restore --verbosity normal

      - uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: src/**/Release/*.nupkg