name: dotnet package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        options:
          - framework: netstandard2.0
    steps:
      - uses: actions/checkout@v3
      - name: DotNetBuild
        shell: pwsh
        run: ./ci-build.ps1 "${{matrix.options.framework}}"
      - name: Test
        run: dotnet test --verbosity normal