name: Build

on:
  workflow_dispatch:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: tree:0

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: NPM Install
        working-directory: ui
        run: npm install
          
      - name: NPM Lint
        working-directory: ui
        run: npm run lint
          
      - name: NPM Build
        working-directory: ui
        run: npm run build
          
      - uses: actions/setup-dotnet@v3

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --no-restore --verbosity normal

      - uses: actions/upload-artifact@v4
        with:
          name: packages
          path: artifacts/*.nupkg

      - name: Pack & Push
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: |
          VERSION_WITHOUT_V=${GITHUB_REF_NAME#v}
          dotnet nuget push "artifacts/*.nupkg" --api-key "${{ secrets.NUGET_APIKEY }}" --source https://api.nuget.org/v3/index.json --skip-duplicate
